name: Testing

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Redis Server in GitHub Actions
      uses: supercharge/redis-github-action@1.4.0
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.12

    - name: Test
      run: go test -v ./...
